site_name: Notas Musicais
repo_url: https://github.com/SilverioSimoes/notas-musicais.git
repo_name: SilverioSimoes/notas-musicais
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css
